etherpad npm install & link ep_etherpad-lite

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -27,6 +27,8 @@ echo $BUILD_DIR
 echo "$(dirname $0)"
 echo "-----> END DEBUG"
 
+
+
 function error() {
   echo " !     $*" >&2
   exit 1
@@ -52,6 +54,18 @@ function run_npm() {
 
   cd $BUILD_DIR
   HOME="$BUILD_DIR" $VENDORED_NODE/bin/node $VENDORED_NPM/cli.js $command 2>&1 | indent
+
+  if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+    echo " !     Failed to $command dependencies with npm"
+    exit 1
+  fi
+}
+
+function run_npm_etherpad() {
+  command="$1"
+
+  cd $BUILD_DIR/$ETHERPAD_MODULE_SRC
+  HOME="$BUILD_DIR/$ETHERPAD_MODULE_SRC" $VENDORED_NODE/bin/node $VENDORED_NPM/cli.js $command 2>&1 | indent
 
   if [ "${PIPESTATUS[*]}" != "0 0" ]; then
     echo " !     Failed to $command dependencies with npm"
@@ -172,17 +186,28 @@ INCLUDE_PATH="$VENDORED_NODE/include"
 export CPATH="$INCLUDE_PATH"
 export CPPPATH="$INCLUDE_PATH"
 
+# link /node_modules/ep_etherpad-lite to ./src 
+echo "-----> Link ep_etherpad-lite module"
+(
+  mkdir -p "$BUILD_DIR/node_modules"
+  ln -v "$BUILD_DIR/node_modules" "$BUILD_DIR/src"
+) || {
+  echo "Link Fail"
+}
+
 # install dependencies with npm
 echo "-----> Installing dependencies with npm"
 
 run_npm "install --production"
 run_npm "rebuild"
+run_npm_etherpad "install --production"
+run_npm_etherpad "rebuild"
 
 echo "-----> START DEBUG"
-echo `pwd` | indent
-echo $BUILD_DIR | indent
-echo $HOME | indent
-echo "-----> END DEBUG" | indent
+echo `pwd`
+echo $BUILD_DIR
+echo $HOME
+echo "-----> END DEBUG"
 
 
 echo "Dependencies installed" | indent
